# Generated by Django 4.1.7 on 2023-03-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0003_item_sizes_pics_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
