# Generated by Django 4.1.7 on 2023-03-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0004_item_size_delete_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='matherial',
            new_name='material',
        ),
        migrations.AddField(
            model_name='composition',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
