# Generated by Django 4.1.7 on 2023-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0005_rename_matherial_composition_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.TextField(choices=[('w', 'Woman'), ('m', 'Man'), ('u', 'Uni'), ('g', 'Girls'), ('b', 'Boys'), ('cu', 'Uni Kids')], default='w'),
        ),
    ]
