# Generated by Django 4.1.7 on 2023-03-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0007_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
